### ISSUE TITLE
[Tracking Issue] Setup iniziale del sito

### ISSUE THREAD

**Issue by Wilkenfeld** [TEDxLuMe/sito#3]
Task per la [Milestone](https://github.com/TEDxLuMe/sito/milestones/1)

### [Sito](https://github.com/TEDxLuMe/sito)
- [ ] https://github.com/TEDxLuMe/sito/issues/1
- [ ] https://github.com/TEDxLuMe/sito/issues/2
- [ ] https://github.com/TEDxLuMe/sito/issues/5

### [Infrastruttura](https://github.com/TEDxLuMe/infrastruttura)
- [ ] https://github.com/TEDxLuMe/infrastruttura/issues/1

### [GoTrue](https://github.com/TEDxLuMe/gotrue)
- [ ] https://github.com/TEDxLuMe/gotrue/issues/1
